replicaCount: 1

image: 
  digest: homebridge/homebridge:latest
  pullPolicy: IfNotPresent

environment:
  pgid: 0
  puid: 0
  ui:
    enabled: 1
    port: 80
  timezone: America/Los_Angeles
  packages: ffmpeg

persist:
  accessories:
    storageClassName: null
  persist:
    storageClassName: null

ports:
  ui:
    name: ui-http
    number: 80
    protocol: TCP

  service:
    name: service-mdns
    number: 51826
    protocol: TCP

service:
  ip:
  annotations: {}

affinity:
  weight: 100
  label: 
  value:

config:
  config: {}
  package: {}
