apiVersion: v1
kind: ConfigMap
metadata:
  name: homebridge-config
data:
  config.json: |
    {{ .Values.config.config | toJson | nindent 4 }}

  package.json: |
    {{ .Values.config.package | toJson | nindent 4 }}

  auth.json: |
    {{ .Values.config.auth | toJson | nindent 4 }}