apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-homekit
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Chart.Name }}

spec:
  selector:
    app: {{ .Chart.Name }}
  externalTrafficPolicy: Local
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.ip }}

  ports:
  - name: {{ .Values.ports.service.name }}
    port: {{ .Values.ports.service.number }}
    protocol: {{ .Values.ports.service.protocol }}
    targetPort: {{ .Values.ports.service.name }}